### PR TITLE
Fee re-fetch improvements

### LINKED ISSUE #456: Fee is queried more than it needs to
**Describe the bug**
It query the API more times than it needs to

**How to Reproduce**
1. Select from/to
2. input sell amount
3. Observe the request done

**Expected behavior**
It should do a single request

**Screenshots**
image

### LINKED ISSUE #472: Delay refreshing the fee quote
**Describe the bug**
There's a delay in the fee quote refreshment

The fee quotes have an expiration date. This date is the moment from which the API will consider the quote not valid any more. I observe that on expiration this refreshment of the quote is not happening right away. There's some kind of delay. 

Furthermore, I think the app should refresh the quote some time before expiration, this way, there's less risks of the operator not accepting the fee. 

**How to Reproduce**

**Expected behavior**
Refresh the fee 30s (configurable) before expiration. I propose 30s because right now the quote is only valid for 1min. I believe the backend will change this time to be bigger. In that case, we can also ask for a new quote a few minutes before expiration.

**Screenshots**
The screenshot shows how the time was greater than the expiration, and still the getFee came after:
Screenshot at Apr 20 16-05-34

By that time, I checked the network tab and there was no request:
Screenshot at Apr 20 16-05-16

### PR DESCRIPTION
**Pull request by anxolin**
## Description
This PR tries to improve the updater of the state for the fee.

There was some issues that motivated this PR (Closes #456, Closes #472)

Additionally, there were some errors reported that the when we sign the transaction, the API doesn't accept the fee amount anymore, this is because the quote expires while the user is signing the trade. To reduce these cases, and to give early feedback to the user, this PR also **Re-fetch a new quote when there's less than 30 seconds left for it's expiration**

## Summary of the new logic
* Makes sure we don't re-fetch the fee if the quote parameters don't change
* ...unless, the quote is about to expire (<30 seconds)
* Adds a periodic check (every 15seconds)

## Some technical hints on the changes
* Refactors the updater. 
   * Same logic is executed for the periodic checks, or for the change of parameters `refetchFeeIfRequired` function 
   * The part of actually making the API call and updating the state was removed from the updater logic. Now it has it's own hook `useRefetchFeeCallback`
   * `isExpiringSoon` and `feeMatchesCurrentParameters` are functions used by the updater to decide if the current quote is still valid.
* The new hook `useRefetchFeeCallback`, now also clears the fee if the API returns `null`. We never notice, but is my understanding that this should be the behaviour

## Changes of state
I notice that the state only had the fee information per sellToken. I included all the other parameters that are required for the API, because now this is actually used to assess if the token information in the state is valid for the current parameters selected in the swap widget.

This is used in `feeMatchesCurrentParameters` in the updater

### CODE REVIEW

File: src/custom/state/fee/updater.ts [hunk 1]
```diff
@@ -1,22 +1,62 @@
...
+/**
+ * Returns true if the fee quote expires soon (in less than RENEW_FEE_QUOTES_BEFORE_EXPIRATION_TIME milliseconds)
+ */
+function isExpiringSoon(quoteExpirationIsoDate: string): boolean {
+  const quoteExpirationDate = Date.parse(quoteExpirationIsoDate)
+  // const secondsLeft = (quoteExpirationDate.valueOf() - Date.now()) / 1000
+  // console.log(
+  //   `[state:fee:updater] Fee isExpiring in ${secondsLeft}. Refetch?`,
+  //   quoteExpirationDate <= Date.now() + RENEW_FEE_QUOTES_BEFORE_EXPIRATION_TIME
+  // )
```
Comment (anxolin) [inline src/custom/state/fee/updater.ts:26]: if it's ok, allow me to leave this dead code, it was useful. It might still be, and it doesn't bother me much as a comment.

Comment (alfetopito) [reply src/custom/state/fee/updater.ts:26]: I wouldn't mind leaving it uncommented

File: src/custom/hooks/useRefetchFee.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+export function useRefetchFeeCallback() {
+  const addFee = useAddFee()
+  const clearFee = useClearFee()
+  registerOnWindow({ addFee })
+
+  return useCallback(
+    async ({ sellToken, buyToken, amount, kind, chainId }: FeeQuoteParams) => {
+      // Get a new quote
+      const fee = await getFeeQuote({ chainId, sellToken, buyToken, amount, kind }).catch(err => {
+        console.error(new Error(err))
```
Comment (alfetopito) [inline src/custom/hooks/useRefetchFee.ts:18]: Do you need to wrap the error?

File: src/custom/state/fee/hooks.ts [hunk 3]
```diff
@@ -1,19 +1,10 @@
...
-interface AddFeeParams extends ClearFeeParams {
-  fee: FeeInformation
-}
-interface ClearFeeParams {
-  token: string // token address,
-  chainId: ChainId
-}
-
 type AddFeeCallback = (addTokenParams: AddFeeParams) => void
 type ClearFeeCallback = (clearTokenParams: ClearFeeParams) => void
```
Comment (alfetopito) [inline src/custom/state/fee/hooks.ts:9]: Since you are here, update the parameters to be inline with the type:

```suggestion
type AddFeeCallback = (addFeeParams: AddFeeParams) => void
type ClearFeeCallback = (clearFeeParams: ClearFeeParams) => void
```

**Review by alfetopito — APPROVED** [review]
Tried it out, working great, only loading once every 15s as promised :+1: 

Question: fees are stored in global state, right? Should it be reused?

Because it doesn't seem to be.

Example:
1. Pick any two tokens
2. Insert 10
3. Right after the fee is loaded, remove a 0
4. Right after the fee is loaded, insert a 0

We should end up with the initial value, and if that's done withing 15s, the first fee should still be valid.
But I noticed a new request for the initial value.

Expected?

File: src/custom/state/fee/updater.ts [hunk 4]
```diff
@@ -1,22 +1,62 @@
...
 import useIsWindowVisible from 'hooks/useIsWindowVisible'
-import { FeesMap } from './reducer'
-import { getFeeQuote, FeeQuoteParams } from 'utils/operator'
-import { registerOnWindow } from 'utils/misc'
 import { Field } from 'state/swap/actions'
 import { useCurrency } from 'hooks/Tokens'
 import useDebounce from 'hooks/useDebounce'
+import { useAllFees } from './hooks'
+import { useRefetchFeeCallback } from '@src/custom/hooks/useRefetchFee'
+import { FeeQuoteParams } from '@src/custom/utils/operator'
```
Comment (W3stside) [inline src/custom/state/fee/updater.ts:10]:
```suggestion
import { FeeQuoteParams } from 'utils/operator'
```

File: src/custom/state/fee/updater.ts [hunk 5]
```diff
@@ -1,22 +1,62 @@
...
 import { useSwapState, tryParseAmount } from 'state/swap/hooks'
 import useIsWindowVisible from 'hooks/useIsWindowVisible'
-import { FeesMap } from './reducer'
-import { getFeeQuote, FeeQuoteParams } from 'utils/operator'
-import { registerOnWindow } from 'utils/misc'
 import { Field } from 'state/swap/actions'
 import { useCurrency } from 'hooks/Tokens'
 import useDebounce from 'hooks/useDebounce'
+import { useAllFees } from './hooks'
+import { useRefetchFeeCallback } from '@src/custom/hooks/useRefetchFee'
```
Comment (W3stside) [inline src/custom/state/fee/updater.ts:9]:
```suggestion
import { useRefetchFeeCallback } from 'hooks/useRefetchFee'
```

File: src/custom/utils/operator.ts [hunk 6]
```diff
@@ -178,16 +178,10 @@ export type FeeQuoteParams = Pick<OrderMetaData, 'sellToken' | 'buyToken' | 'kin
...
-export async function getFeeQuote({
-  sellToken,
-  buyToken,
-  amount,
-  kind,
-  chainId
-}: FeeQuoteParams): Promise<FeeInformation> {
-  const independentToken = kind === 'buy' ? buyToken : sellToken
+export async function getFeeQuote(params: FeeQuoteParams): Promise<FeeInformation> {
+  const { sellToken, buyToken, amount, kind, chainId } = params
```
Comment (W3stside) [inline src/custom/utils/operator.ts:182]: you really hate destructuring in the signature don't you

**Review by W3stside — APPROVED** [review]

File: src/custom/utils/operator.ts (hunk 6 above)
Comment (anxolin) [reply src/custom/utils/operator.ts:182]: Hehe, I love it, I just a super low threshold in which I move things away from the function definition

In this case was mostly motivated for printing all the params in the log

**Comment by anxolin** [comment]
> Question: fees are stored in global state, right? Should it be reused?

It could but is not. Before it was easier to reuse. Now of course we could retain all unexpired quotes, but I think the change would be more complicated, ergo out of this scope. I say this, cause we would like to remove keys on expiration, not leave them there forever. It wouldn't be that hard, but considering the gain (only if the user type the same thing, u save a request that is already super fast), and the loss (develop time, possible errors, more storage) I felt it was not something for now. 

But good catch, I also considered to do that :)

File: src/custom/hooks/useRefetchFee.ts (hunk 2 above)
Comment (anxolin) [reply src/custom/hooks/useRefetchFee.ts:18]: Ouch, missed some comments. No, I will address in another PR. 
I don't even remember doing that!

Comment (anxolin) [reply src/custom/hooks/useRefetchFee.ts:18]: https://github.com/gnosis/gp-swap-ui/pull/482
