### PR TITLE
[ETH/WETH] Confirmation Modal

### LINKED ISSUE #348: Wrapping max  amount of ETH
# Description
When wrapping the max amount of ETH the gas fee is not considered when connected via Portis. 

# How to Reproduce
- Connect with Portis Wallet
- Select Eth as from token 
- follow Wrap Eth instructions
- Choose max amount of Eth
- Click on wrap

# Observed Behaviour:
Portis pop up shows up indicating, that you don't have enough funds

# Expected Behaviour:
The max value for wrapping Eth should consider the gas fee and deduct it from the total amount.
This is done when you are connected via MM

# Screenshots/Videos
How it behaves in MM 
Bildschirmfoto 2021-03-26 um 12 35 58

How it looks like in Portis
Bildschirmfoto 2021-03-26 um 12 32 07

### PR DESCRIPTION
**Pull request by W3stside**
Closes #348 

Warning using calculated threshold: 
```bash
THRESHOLD_LOW_BALANCE = 10 * 50000 * 1e9
ETH_THRESHOLD_WEI = GAS_PRICE * THRESHOLD_LOW_BALANCE
```

## Warning shown, before modal:
Screenshot from 2021-04-27 19-10-13

## Warning in confirmation modal
Screenshot from 2021-04-27 19-10-21

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
wow, looks great! way better than I thought about it. I just though about a basic confirm modal, so good you reuse the wrapping info. 

I'll do a proper review tomorrow, but today an early feedback:
- I would add a cancel button
- I wouldn't show the exact number of what we consider "low balance" since this is a subjective number

File: src/custom/components/swap/EthWethWrap/helpers.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+export const DEFAULT_GAS_FEE = parseUnits('50', 'gwei')
+
+export const setNativeLowBalanceError = (nativeSymbol: string, lowBalanceThreshold: CurrencyAmount) =>
+  new Error(
+    `WARNING! After wrapping your ${nativeSymbol}, your balance will fall below < ${lowBalanceThreshold.toSignificant(
+      DEFAULT_PRECISION
+    )} ${nativeSymbol}. As a result you may not have sufficient ${nativeSymbol} left to cover future on-chain transaction costs.`
+  )
+
+export function checkUserBalance({
```
Comment (alfetopito) [inline src/custom/components/swap/EthWethWrap/helpers.ts:16]: Since it returns a boolean, could you rename it so it expresses what's the result?
Right now I don't know whether `true` is good or bad.

Maybe `isBalanceEnough` or `shouldDisplayLowBalanceWarning`

File: src/custom/components/swap/EthWethWrap/helpers.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  txCost,
+  userInput,
+  balance
+}: {
+  threshold: CurrencyAmount
+  txCost: CurrencyAmount
+  userInput?: CurrencyAmount
+  balance?: CurrencyAmount
+}) {
+  if (!userInput || !balance || userInput.add(txCost).greaterThan(balance)) return true
```
Comment (alfetopito) [inline src/custom/components/swap/EthWethWrap/helpers.ts:27]: Why is this true? `userInput.add(txCost).greaterThan(balance)`

Doesn't `input + cost > balance` mean the user has no balance to cover the tx?

**Review by alfetopito — APPROVED** [review]
Only a small note regarding the helper function naming.
Otherwise, looks good to me.

File: src/custom/components/swap/EthWethWrap/helpers.ts (hunk 2 above)
Comment (W3stside) [reply src/custom/components/swap/EthWethWrap/helpers.ts:27]: Function should be `isLowBalance`

**Comment by biocom** [comment]
Couple of notes:

- I'd add a X close icon in the right corner. Just like we have in the token selector list.
- I think as @anxolin mentioned, it would be good to have a cancel text link, below the blue button.
- It would be good to make it clear, what the primary action is of this modal. We can do this by adding a title: "Confirm wrapping ETH" just like the regular confirmation modals have this type of titles.

**Comment by W3stside** [comment]
> * I would add a cancel button
ok
> * I wouldn't show the exact number of what we consider "low balance" since this is a subjective number
mm but this will likely cause the same issue of "it shows me one state and i dont know why" and we'll end up making a hotfix to show the number. I'd suggest we just use less opinionated language and say "we recommend having at least" or sth idk
> * Instead of a "smooth experience" is more like, to be able to "enable trading" for the tokens, or for new "wrapping/unwrapping".  Maybe we can look for a better message
ok can reword, just wrote sth quickly here

File: src/custom/components/swap/EthWethWrap/helpers.ts (hunk 1 above)
Comment (W3stside) [reply src/custom/components/swap/EthWethWrap/helpers.ts:16]: :+1:

**Comment by anxolin** [comment]
> mm but this will likely cause the same issue of "it shows me one state and i don't know why" and we'll end up making a hotfix to show the number. I'd suggest we just use less opinionated language and say "we recommend having at least" or sth idk

We can ask around. The estimation does't say much. Why we recommend 10 tx and not 2 or 20? 

More advance would be to express it in your remaining balance would allow you to do less than XXX transfers or enabling YYYY tokens. 
I don't say you are not right and someone might ask for that, but if we frase it correctly and we just show that he is running low, he can see his balance and decide if he agrees. We don't need to tell how much we consider low. It would be just more numbers to confuse the user (he already has eth balance, weth balance, eth to wrap, so introducing a new number I find it more confusing)

**Comment by anxolin** [comment]
My text suggestion:
`At current gas prices, your remaining ETH will only allow you to do XXX wrapping/unwrapping or enabling XXX tokens for trading."

**Comment by W3stside** [comment]
> Although cow swap doesn't need ETH for trading (gasless trading!), **ETH is used for enabling tokens for trading and for wrapping/unwrapping ETH into WETH**.

Cow Swap is a gasless exchange. **ETH however, is required to pay for the on-chain transaction costs associated with enabling tokens and for the wrapping/unwrapping of ETH/WETH, respectively.**  
> At current gas prices, your remaining ETH will only allow you to do `XXX` wrapping/unwrapping operations or enabling YYY` tokens for trading.

At current gas prices, your remaining ETH is sufficient for up to `XXX` wrapping/unwrapping/enabling operations.
> Are you sure you want to leave XXX ETH in your wallet after this Wrapping?

Are you sure you want to continue and leave XXX ETH in your wallet after this operation?
> [No], [Yes, wrap anyways]

[No], [Yes, continue wrapping]

**Comment by anxolin** [comment]
I like more yours, nice @W3stside 

@annamsgeorge, can you double check?

**Comment by annamsgeorge** [comment]
Very cool! I agree, @W3stside 's language is good to go with.

**Review by anxolin — APPROVED** [review]

**Review by biocom — APPROVED** [review]
