### PR TITLE
Fixed issues with order validTo:

### LINKED ISSUE #214: Issue with expire date
Somehow @fleupold managed to create an order with 85 years as the expiration date

Two questions come to mind:
- 1. where did this error ocur, backend/frontend?
- 2. Why 85 years?

**1) It is probably a frontend issue**
The backend cannot modify the expiration date. Although, this is assuming the backend stored correctly the expiration date in their DB. So a quick review in the smart contract would answer if this order expiration date was so big. 

If the smart contract tell us is a big expiration date, it's 100% the frontend. Since the backend cannot modify the signed data. 

**2) Felix mentioned is because is the maximum amount they allow**
However, we might want to review this part, because the backend shouldn't modify what is in the smart contract. 

Unless, this is the true maximum in the smart contract, then is all fine!

EDIT: It's all fine with question number 2, since the datatype is `uint32`, which yields this max value:
image

### LINKED ISSUE #231: Issue with "valid to": Error 500 for duplicated orders
If we send 2 times the same order, and we do it FAST, we will get an error from the backend (error `500`). 

image

This is because the ID is dependent on the hash of the order details.
I believe the cause of this issue is because we should at least change the `validTo` date, and we don't. `validTo` should be re-calculated in the second transaction (but it didn't happen)

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #214 
Closes #231

- No longer defaults to max uint32 when value is not set
- No longer depends on block timestamp. Uses browser time instead
- Calculating validTo when the order is placed instead of caching it on
  a hook
- When user set a deadline that would overflow uint32, cap it to max
  uint32

# Testing

## Validating #214

1. On trade settings, set a value greater than `44659000`
screenshot_2021-03-11_10-58-34

2. Pick two tokens, set the amount, and swap it
- [ ] On the signature request, confirm the `validTo` field is set to `4294967295`
screenshot_2021-03-11_10-59-25

3. Sign the trade and check the explorer link
- [ ] Expiration date should be 85 years (example: https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x31b75dba1e0bae6281db8414b7ce004989275c68111415e056e792053a9377b75b0abe214ab7875562adee331deff0fe1912fe42ffffffff)
screenshot_2021-03-11_11-00-50

4. Repeat steps `1` through `3` with different deadline values, all greater than `4294967295`
- [ ] The resulting signature and explorer expiration date should all be identical

## Validating #231

1. Fill in the trade with tokens and amount
2. Submit the trade and sign it
3. Very quickly, repeat the process with exactly same parameters
- [ ] Two independent trades should be placed
- [ ] Verify their explorer links point to different orders

Example:
1. https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xbfbc701c4d01da5bf8f22c922988291cef12c9eca3ccf1b5af952f634d0cef335b0abe214ab7875562adee331deff0fe1912fe42604a66c1
2. https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x2d385d34d5003f23ff3fe8a0e629fa7413acb46fcc8338b92172a3c8133f6ccd5b0abe214ab7875562adee331deff0fe1912fe42604a66cb

### CODE REVIEW

**Review by W3stside — APPROVED** [review]

File: src/custom/hooks/useSwapCallback.ts [hunk 1]
```diff
@@ -17,9 +15,20 @@ import { computeSlippageAdjustedAmounts } from 'utils/prices'
 import { postOrder } from 'utils/trade'
 import { OrderKind } from 'utils/signatures'
 import { TradeWithFee } from 'state/swap/extension'
+import { useUserTransactionTTL } from '@src/state/user/hooks'
+import { BigNumber } from 'ethers'
 
 const MAX_VALID_TO_EPOCH = BigNumber.from('0xFFFFFFFF').toNumber() // Max uint32 (Feb 07 2106 07:28:15 GMT+0100)
 
+function calculateValidTo(deadline: number): number {
```
Comment (anxolin) [inline src/custom/hooks/useSwapCallback.ts:23]: Should this be a util instead?

**Review by anxolin — APPROVED** [review]
Works perfectly!
