### PR TITLE
Fix non-valid Price fetch amount, fix fee 2 times

### LINKED ISSUE #547: The fee field is shown two times
**Describe the bug**
The fee field is shown two times

**How to Reproduce**
See conversation and video:
https://gnosisinc.slack.com/archives/CSGLUC1BN/p1619533192019200

**Screenshots**
image

### LINKED ISSUE #604: Price/fee is wrong when swapping tokens
**Describe the bug**

**How to Reproduce**
https://github.com/gnosis/gp-swap-ui/pull/602#pullrequestreview-653704054

### LINKED ISSUE #637: Wrong notification for Fees exceeding from amount
**Describe the bug**
Insufficient liquidity for this trade is displayed when actually the fees exceed the amount

**How to Reproduce**
1. Enter an amount close to the fee amount as from token
2. Insufficient liquidity for this trade is displayed

**Expected behavior**
Fees exceed from amount should be displayed instead

**Screenshots**
Bildschirmfoto 2021-05-18 um 10 20 06
Bildschirmfoto 2021-05-18 um 10 20 28

### PR DESCRIPTION
**Pull request by W3stside**
Closes #547
Closes #637
May close #604, needs to be tested moar

This fixes several things:
1. more accurately show fee and fee exceed from amount in button when the user's input amount is indeed <= fee amount from API
2. price returned null if step 1 == true
3. if (fee.exists BUT !price) = feeExceedsPrice
4. dont use parsed amount as fee token, always use sellToken
5. dont query endpoint with negative amount, check before

To test:
1. WETH <> DAI
2. sell tiny amount
3. observe networks tab: no fetching if price <= fee amount
4. fee > input error correct in button 
5. fee shows correct amounts checkable against networks returned data for fee amount
6. fee token name correct (always sell)

### CODE REVIEW

File: src/custom/utils/operator/index.ts [hunk 1]
```diff
@@ -151,17 +151,19 @@ function toApiAddress(address: string, chainId: ChainId): string {
 
 async function _getJson(chainId: ChainId, url: string): Promise<any> {
   let response: Response | undefined
+  let json
   try {
     response = await _fetchGet(chainId, url)
+    json = await response.json()
```
Comment (alfetopito) [inline src/custom/utils/operator/index.ts:157]: I think this throws is the response doesn't have a body, doesn't it?

Comment (W3stside) [reply src/custom/utils/operator/index.ts:157]: shouldn't that be expected? i.e if no body = no data = error no?

File: src/custom/hooks/useRefetchPriceCallback.ts [hunk 2]
```diff
@@ -125,7 +132,10 @@ export function useRefetchQuoteCallback() {
           price,
           chainId,
           lastCheck: Date.now(),
-          fee
+          fee,
+          // if we get a fee back but no price, its a fee issue
+          // otherwise it would be a handled api error
+          feeExceedsPrice: Boolean(!price && fee)
```
Comment (anxolin) [inline src/custom/hooks/useRefetchPriceCallback.ts:138]: We have the amount, and we have the fee. Shouldn't this be based on the `amout-fee <= 0` instead of assuming that if price is null, is because fees a re bigger than amount?

File: src/custom/hooks/useRefetchPriceCallback.ts [hunk 3]
```diff
@@ -35,16 +35,22 @@ async function getQuote({
...
   if (kind === 'sell') {
     // Sell orders need to deduct the fee from the swapped amount
-    exchangeAmount = BigNumber.from(amount)
-      .sub((await feePromise).amount)
-      .toString()
+    // we need to check for 0/negative exchangeAmount should fee >= amount
+    const { amount: fee } = await feePromise
+    const result = BigNumber.from(amount).sub(fee)
+
+    const validQuery = result.gt('0')
```
Comment (anxolin) [inline src/custom/hooks/useRefetchPriceCallback.ts:42]: can you give a more semantic name? --> i.e `positiveExchangeAmount`

Comment (anxolin) [reply src/custom/hooks/useRefetchPriceCallback.ts:42]: O use the name you used in the other method `feeExceedsPrice` and actually you can even return this, so you can use it directly (instead of relying on assuming that a null price is because `feeExceedsPrice`

**Review by anxolin — APPROVED** [review]
Approving, just some minor comments

File: src/custom/hooks/useRefetchPriceCallback.ts (hunk 3 above)
Comment (W3stside) [reply src/custom/hooks/useRefetchPriceCallback.ts:42]: true, good points

Comment (W3stside) [reply src/custom/hooks/useRefetchPriceCallback.ts]: https://github.com/gnosis/gp-swap-ui/pull/645/commits/4d43b2dd7c4b2c94b2a22a9ca212cd80838ad1e6

File: src/custom/hooks/useRefetchPriceCallback.ts (hunk 2 above)
Comment (W3stside) [reply src/custom/hooks/useRefetchPriceCallback.ts]: fixed in https://github.com/gnosis/gp-swap-ui/pull/645#discussion_r635168532

File: src/custom/utils/operator/index.ts (hunk 1 above)
Comment (alfetopito) [reply src/custom/utils/operator/index.ts:157]: Yeah, but aren't you counting on the body to extract the error message?

For example, 404 would have no body, and still not (be expected to) throw.
