### PR TITLE
[165] Expired Order delay

### LINKED ISSUE #165: Race conditions: 🐎 Cancelations, and Fullfillment
image

As you see in the image, my trade got both EXPIRED and FULFILLED.

This is obviously an error. The cancelation toast should have a small delay, giving chance to the potential fulfillment to arrive. 

Fullfillement is dependent on events, that can have some latencies. Also, blocks are not EXACTLY mined at the time they claim. So it would be wise to give some time extra for the the fulfillment to arrive. 

**TIMELINE (now):**
- 1. Send order
- 2. Filled but the event hasn't arrived yet
- 3. Expiration kicks in ---> we show toast of EXPIRED
- 4. [5 sec later] Receive event of "Filled" ---> we show toast of FILLED

**TIMELINE (proposal):**
- 1. Send order
- 2. Filled but the event hasn't arrived yet
- 3. Expiration kicks in ---> Delay (20s) and then check order if still exipred ---> we show toast of EXPIRED
- 4. [5 sec later]  Receive event of "Filled" ---> we show toast of FILLED

## QA Testing notes
- Verify we don't get notifications twice for trades
- We can try to reduce the expiration to 1min trying to reproduce this issue
Testing URL https://pr269--gpswapui.review.gnosisdev.com/

### PR DESCRIPTION
**Pull request by W3stside**
Closes #165 - Order X has expired message shown followed by a fulfilled order message due to race conditions

This PR doesn't address the race condition underlying issue as that is a more extensive fix for later. I believe for the forementioned, a good solution could (waiting on confirmation) be querying the `orders` endpoint and checking the `OrderMetaData["invalidated"]` prop, which, if reliable, would allow us to check against potentially `expired` orders list if they are indeed `invalidated`

However this fix adds a `BUFFER` time in MS to the user selected `validTo` (2minutes right now) and uses that to check if an expired order notification should be sent out

### CODE REVIEW

**Comment by anxolin** [comment]
One quick feedback:

"invalidated" is different to "expired"  as mentioned here https://gnosisinc.slack.com/archives/CPZA1AGKY/p1615990292008700

The solution sounds ok to me. But imo 2min is too much. I would expect to have it mined in the next block, maybe considering reorgs we can add 45 seconds. 
Does this delay the notification (popup) or also the status in the recent trades?

File: src/custom/constants/index.ts [hunk 1]
```diff
@@ -40,3 +40,4 @@ export const BUY_ETHER_TOKEN: { [chainId in ChainId]: Token } = {
 export const ORDER_ID_SHORT_LENGTH = 8
 export const INPUT_OUTPUT_EXPLANATION = 'Only executed swaps incur fees.'
 export const DEFAULT_ORDER_DELAY = 20000 // 20s
+export const EXPIRED_ORDERS_BUFFER = 60 * 2 * 1000 // 2 minutes
```
Comment (anxolin) [inline src/custom/constants/index.ts:43]: I think 45s would suffice

File: src/custom/state/orders/updater.ts [hunk 2]
```diff
@@ -312,7 +326,8 @@ export function ExpiredOrdersWatcher(): null {
         // validTo is either a Date or unix timestamp in seconds
         const validTo = typeof order.validTo === 'number' ? new Date(order.validTo * 1000) : order.validTo
 
-        return validTo < now
+        // let's get the current date, with our expired order validTo given a buffer time
```
Comment (anxolin) [inline src/custom/state/orders/updater.ts:329]: Not from this PR, but we should move this CHECK_EXPIRED_ORDERS_INTERVAL to our constant file too

File: src/custom/state/orders/updater.ts [hunk 3]
```diff
@@ -312,7 +326,8 @@ export function ExpiredOrdersWatcher(): null {
...
+        return _validToWithBuffer(validTo, EXPIRED_ORDERS_BUFFER) < now
```
Comment (anxolin) [inline src/custom/state/orders/updater.ts:330]: I don't think we need to construct a new date. We can substract the 2 dates, and see if the difference if greater than the buffer

**Review by anxolin — COMMENTED** [review]
Good PR! just minor comments

File: src/custom/state/orders/updater.ts (hunk 3 above)
Comment (W3stside) [reply src/custom/state/orders/updater.ts:330]: :+1:

File: src/custom/state/orders/updater.ts (hunk 2 above)
Comment (W3stside) [reply src/custom/state/orders/updater.ts:329]: :+1:

File: src/custom/constants/index.ts (hunk 1 above)
Comment (W3stside) [reply src/custom/constants/index.ts:43]: :+1:

**Review by anxolin — APPROVED** [review]
