### PR TITLE
[165::Bug fix] - Delay querying backend for fulfilled order data

### LINKED ISSUE #165: Race conditions: 🐎 Cancelations, and Fullfillment
image

As you see in the image, my trade got both EXPIRED and FULFILLED.

This is obviously an error. The cancelation toast should have a small delay, giving chance to the potential fulfillment to arrive. 

Fullfillement is dependent on events, that can have some latencies. Also, blocks are not EXACTLY mined at the time they claim. So it would be wise to give some time extra for the the fulfillment to arrive. 

**TIMELINE (now):**
- 1. Send order
- 2. Filled but the event hasn't arrived yet
- 3. Expiration kicks in ---> we show toast of EXPIRED
- 4. [5 sec later] Receive event of "Filled" ---> we show toast of FILLED

**TIMELINE (proposal):**
- 1. Send order
- 2. Filled but the event hasn't arrived yet
- 3. Expiration kicks in ---> Delay (20s) and then check order if still exipred ---> we show toast of EXPIRED
- 4. [5 sec later]  Receive event of "Filled" ---> we show toast of FILLED

## QA Testing notes
- Verify we don't get notifications twice for trades
- We can try to reduce the expiration to 1min trying to reproduce this issue
Testing URL https://pr269--gpswapui.review.gnosisdev.com/

### PR DESCRIPTION
**Pull request by W3stside**
Branched off of #192 

Potentially closes #165 

Delays the querying of the backend for a detected fulfilled order (20 second delay)

Difficulty: how to test this is actually working and now still just a race condition?

### CODE REVIEW

File: src/custom/state/orders/updater.ts [hunk 1]
```diff
@@ -21,6 +21,7 @@ import { stringToCurrency } from '../swap/extension'
 type OrderLogPopupMixData = OrderFulfillmentData & Pick<Log, 'transactionHash'> & Partial<Pick<Order, 'summary'>>
 
 const TradeEvent = GP_V2_SETTLEMENT_INTERFACE.getEvent('Trade')
+const DEFAULT_ORDER_DELAY = 20000 // 20 seconds
```
Comment (anxolin) [inline src/custom/state/orders/updater.ts:24]: consider moving to const

**Review by anxolin — APPROVED** [review]
I'm good with this PR, but I believe we need something more robust aligned with the ideas in https://github.com/gnosis/gp-swap-ui/issues/213

File: src/custom/state/orders/updater.ts (hunk 1 above)
Comment (W3stside) [reply src/custom/state/orders/updater.ts:24]: > I'm good with this PR, but I believe we need something more robust aligned with the ideas in #213

I'll add a comment that this is a temporary fix

**Review by alfetopito — APPROVED** [review]
