### PR TITLE
662 - Dancing Numbers!

### LINKED ISSUE #662: Issue with dancing values 💃
**Describe the bug**
The FROM or TO inputs in the widgets get sometimes a very wrong value. Then the issue is solved automatically.

**How to Reproduce**
1. Select any token pair. Input a value in the TO to make a buy order
2. Then input another very different value in the FROM
3. Notice how the old from value "jumped" to the TO, then once the new TO is calculated, the value is updated to the right value.

Maybe we should just make it blank the field when is not calculated yet? (or a spinner)?

https://user-images.githubusercontent.com/2352112/118989451-5782a980-b982-11eb-8d3c-2dffe809bdce.mp4

### PR DESCRIPTION
**Pull request by W3stside**
Closes #662 - merges into #668 or should merge into develop after #668

Addresses dancing numbers which was a result of the `useDebounce` hook caching the last value. Why was this an issue? When switching trade types, e.g inputting something into the BUY input after initially inputtin sth in the SELL input would send a quote request using the last SELL input amt to the backend returning sometimes outlandish amounts for a few seconds, before recalculating the correct amounts.

The new hook, `useDebounceWithForceUpdate` (epic name) has a force arg that allows the last amount to be used and bypasses the debounce.

This also returns `null` on `quoteLoading` to reset the field

### CODE REVIEW

**Comment by alfetopito** [comment]
It doesn't look like it's debouncing at all for me.
Every single keypress triggers new requests, doesn't matter how fast.

File: src/custom/hooks/useDebounceWithForceUpdate.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
+import { useEffect, useState } from 'react'
+
+// modified from https://usehooks.com/useDebounce/
+export default function useDebounceWithForceUpdate<T>(
+  value: T,
+  delay: number,
+  forceUpdateRef?: string | number | boolean
```
Comment (anxolin) [inline src/custom/hooks/useDebounceWithForceUpdate.ts:7]: a bit weird signature. Probably this can be `any` type, since it's what useEffects accepts

why `Boolean(forceUpdateRef)`?  this is a general hook. If `forceUpdateRef` chanfges from `'something'` to `''` then you wipn't force the update, right?

File: src/custom/hooks/useDebounceWithForceUpdate.ts [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+    ) {
+      setDebouncedValue(value)
+      setLastForceUpdateRef(forceUpdateRef)
+    }
+  }, [debouncedValue, forceUpdateRef, lastForceUpdateRef, value])
+
+  // Update debounced value after delay
+  useEffect(() => {
+    const handler = setTimeout(() => {
+      setDebouncedValue(value)
```
Comment (anxolin) [inline src/custom/hooks/useDebounceWithForceUpdate.ts:26]: Don't you need to set the last forced value? although I think we probably don't need two states...

File: src/custom/hooks/useDebounceWithForceUpdate.ts [hunk 3]
```diff
@@ -0,0 +1,38 @@
+import { useEffect, useState } from 'react'
+
+// modified from https://usehooks.com/useDebounce/
+export default function useDebounceWithForceUpdate<T>(
+  value: T,
+  delay: number,
+  forceUpdateRef?: string | number | boolean
+): T {
+  const [lastForceUpdateRef, setLastForceUpdateRef] = useState(forceUpdateRef)
+  const [debouncedValue, setDebouncedValue] = useState<T>(value)
```
Comment (anxolin) [inline src/custom/hooks/useDebounceWithForceUpdate.ts:10]: Why 2 states? if we have only one value, we update it eagerly when ref changes, and with a delay when it doesn't

**Comment by anxolin** [comment]
#691 I've made this proposal for the hook implementation.

**Comment by anxolin** [comment]
@davidalbela  I merged my PR into yours because I thought this branch was based in develop, so i was planning to merge your PR too to develop for the release. Then I will wait for you...

I hope is not too bad, otherwise I can revert it easily

**Review by anxolin — APPROVED** [review]
