### PR TITLE
[148] Fix undefined order toast

### LINKED ISSUE #148: Error in message: Undefined fullfilled
image

### PR DESCRIPTION
**Pull request by W3stside**
Closes #148 

Creates `shortenOrderId` fn 
Checks computed `summary` var to make sure it isn't `falsy` then returns better data:

### Screenshot shows `0x` before order id but that is removed in last commit 

Screenshot from 2021-02-15 09-28-42

### CODE REVIEW

File: src/custom/state/orders/middleware.ts [hunk 1]
```diff
@@ -56,7 +57,7 @@ export const popupMiddleware: Middleware<{}, AppState> = store => next => action
         metatxn: {
           id,
           success: true,
-          summary: summary + ' submitted' || `Order ${id} submitted`
```
Comment (anxolin) [inline src/custom/state/orders/middleware.ts:59]: lot of repetition, isn't it? can we DRY it a bit 🌬

File: src/custom/utils/index.ts [hunk 2]
```diff
@@ -79,3 +79,7 @@ export function getEtherscanLink(chainId: ChainId, data: string, type: BlockExpl
     return getEtherscanUrl(chainId, data, type)
   }
 }
+
+export function shortenOrderId(orderId: string, chars = 4, length = 114): string {
```
Comment (anxolin) [inline src/custom/utils/index.ts:83]: magic number, actually I have this const in one PR, maybe we just add it to our constants and then we both use it 
https://github.com/gnosis/gp-swap-ui/pull/147

anyways, why length is given instead of using orderId.length?
Also, this is not how we shorten orderIds. I believe we don't show the 0x and we show 8 characters.

Comment (W3stside) [reply src/custom/utils/index.ts:83]: As the description states and the `2` indicates, there is no 0x, will make 8 and use the const

File: src/custom/utils/index.ts [hunk 3]
```diff
@@ -88,3 +88,9 @@ export function getEtherscanLink(chainId: ChainId, data: string, type: BlockExpl
     return getEtherscanUrl(chainId, data, type)
   }
 }
+
+// Shortens OrderID (or any string really) removing initial 2 characters e.g 0x
+// and cutting string at 'chars' length, default = 8
+export function shortenOrderId(orderId: string, chars = 8): string {
+  return orderId.substring(2, chars)
+}
```
Comment (alfetopito) [inline src/custom/utils/index.ts:96]: Is it possible the orderId will ever not have the `0x` prefix?
In case, might be safer to "trim" `0x` from the start only if present

**Review by alfetopito — APPROVED** [review]

File: src/custom/utils/index.ts (hunk 3 above)
Comment (anxolin) [reply src/custom/utils/index.ts:96]: Actually. Why don't we trim it when we receive it from the backend? We normalize the orderId when is returned.

**Comment by W3stside** [comment]
@anxolin @alfetopito I opted to keep the formatting fo the OrderID in the middleware and NOT at the "source" - as there are too many places this breaks and requires formatting:
1. listening to logs in `orders/Updater` 
and in the actions used: 
2. fulfillOrdersBatch and 
3. expiredOrdersBatch, inside trade.ts etc. 

If we really want to change this later, let's do it, just not now

**Review by anxolin — APPROVED** [review]
