### PR TITLE
[FIX] Buy order incorrect numbers + use slippage adjusted amounts

### LINKED ISSUE #369: Sell amounts is incorrect in buy orders
Sell amounts is incorrect in buy orders

One easy way to see the problem is to choose the FAKE DAI, and try to buy 100 DAI using OWL:
In uniswap we can see how to buy this DAI we almost don't need to pay any OWL:
image

The information in the confirm modal is correct:

We have to pay more than uniswap 0.144524  OWL. We can easily see that what we pay is almost entirely because of fees:
* max sold: 0.1452 OWL
* fee: 0.144518 OWL
image

So what we REALLY sell is 0.000682 OWL. old the rest are fees. 
However, we sign the order, we forgot to deduct the fees:
image

cc/ @nlordell

### LINKED ISSUE #370: The slippage has no effect in buy orders
image
image

The above 2 pictures shows two buy orders with same amounts, same prices, the only difference is the slippage. 
Although the slippage is correctly applied in the confirmation modal, the signed amounts are exactly the same, what is obviously an error. 

We should make also another review to sell orders.

cc/ @nlordell

### PR DESCRIPTION
**Pull request by W3stside**
Closes #369 and closes #370 

Logic wasn't sending the SELL or BUY amounts with slippage applied to the API. It was sending the expected amounts with no adjustment for slippage - this PR sends the correct values.

To test: (RINKEBY::WETH for USDC)
`SELL`
1. Set a high slippage amount, say 49% and confirm it shows that on swap
2. Set WETH sell to `0.0005`
3. Make sure all params are correct: minimum received should be the displayed `To` amount computed with slippage:
assuming `To` amount shows `0.251709`, then:
```
0.251709 * (1 + 0.49) = 0.1689 USDC
```
4. Submit the order
5. Check that the confirmation modal screens show correct numbers
6. Click `Confirm swap`
7. looks at the MM popup and make sure that the:
  a. `sellAmount` + `feeAmount` = the amount you initially input (it will be shown in atoms)
  b. that the buyAmount is the SLIPPAGE adjusted amount we calculated in step 3

`BUY`
1. Set a high slippage amount, say 49% and confirm it shows that on swap
2. Set USDC buy to `0.251709`
3. Make sure all params are correct: maximum sold should be the displayed `From` amount computed with slippage:
assuming `From` amount shows `0.000504998`, then:
```
0.000504998 * (1 + 0.49) = 0.0007524 WETH
```
4. Submit the order
5. Check that the confirmation modal screens show correct numbers
6. Click `Confirm swap`
7. looks at the MM popup and make sure that the:
  a. `sellAmount` + `feeAmount` = the slippage adjusted sell amount in atoms
  b. that the buyAmount is the exact amount you input initially in step 2

For both: check that the toast notification messages show the fee adjusted amounts and the slippage adjusted amounts correctly

EDIT: leandro schooled me in maths

### CODE REVIEW

File: src/custom/hooks/useSwapCallback.ts [hunk 1]
```diff
@@ -29,6 +29,26 @@ function calculateValidTo(deadline: number): number {
...
 
+const _computeInputAmountForSignature = (params: {
+  input: CurrencyAmount
+  inputWithSlippage: CurrencyAmount
+  fee?: CurrencyAmount
+  kind: OrderKind
+}) => {
+  const { input, inputWithSlippage, fee, kind } = params
+  // When POSTing the order, we need to check inputAmount value depending on trade type
+  // If we don't have an applicable fee amt, return the inputAmount adjusted for fee
```
Comment (alfetopito) [inline src/custom/hooks/useSwapCallback.ts:40]: From how it's implemented it looks like this comment is outdated.

```suggestion
  // If we don't have an applicable fee amt, return the input as is
```

**Review by alfetopito — APPROVED** [review]
Tested with a BUY order. Worked great!

Step by step:

## Inputs
screenshot_2021-04-01_09-53-39
## Confirmation
screenshot_2021-04-01_09-53-53
## Wallet pending modal
:warning: Note that here the amount displayed is the input amount (without slippage, with fees)
screenshot_2021-04-01_09-54-04
## MM signature request
screenshot_2021-04-01_09-54-11
## Order submitted toast
:warning: Note that here the value displayed is the total (with slippage, with fees)
screenshot_2021-04-01_09-54-22

## Order matched toast
:warning: Note that here the amount is the actual traded amount (with fees)
screenshot_2021-04-01_09-55-05
## BONUS: explorer with BUY order surplus (https://github.com/gnosis/gp-ui/pull/349)
screenshot_2021-04-01_09-57-15

**Review by biocom — APPROVED** [review]
