### PR TITLE
Fix token approval link

### LINKED ISSUE #237: Token Approval Notification link shows Etherscan but links to GP Explorer

### PR DESCRIPTION
**Pull request by anxolin**
Closes #237 , supersedes #248

### CODE REVIEW

**Comment by W3stside** [comment]
@anxolin did you check this works though? with `approve` vs `submit meta tx` vs `fulfilled tx`

**Review by W3stside — APPROVED** [review]

File: src/custom/components/ExplorerLink/index.tsx [hunk 1]
```diff
@@ -22,5 +21,5 @@ export function ExplorerLink(props: Props) {
   }
 
   const linkLabel = label || getExplorerLabel(chainId, id, type)
-  return <ExternalLink href={getExplorerOrderLink(chainId, id)}>{linkLabel}</ExternalLink>
+  return <ExternalLink href={getEtherscanLink(chainId, id, type)}>{linkLabel}</ExternalLink>
```
Comment (alfetopito) [inline src/custom/components/ExplorerLink/index.tsx:24]: Well, this fixed the issue but the code seems to be wrong, if we think about the function name.
What about renaming [`getEtherscanLink`](https://github.com/gnosis/gp-swap-ui/blob/release%2F0.6.0/src/custom/utils/index.ts#L83) to `getExplorerLink` ?
